load("@rules_nodejs//nodejs:defs.bzl", "npm_package")

package(default_visibility = ["//visibility:public"])

npm_package(
    name = "website-package",
    srcs = glob([
        "**/*",
    ]),
    package_name = "interview-ai-website",
)




